- name: "type:bug"
  color: "d73a4a"
  description: "Fehlerbericht"
- name: "type:feature"
  color: "a2eeef"
  description: "Neues Feature"
- name: "scope:ui/ux"
  color: "cfd3d7"
  description: "Frontend/Design"
- name: "prio:triage"
  color: "fbca04"
  description: "Muss bewertet werden"
