blank_issues_enabled: false
contact_links:
  - name: 📚 Dokumentation
    url: https://example.invalid/docs
    about: Lese zuerst die Projekt-Dokumentation.
  - name: 💬 Diskussion
    url: https://example.invalid/discussions
    about: Stelle Fragen oder starte eine Diskussion.
