name: CI – React/Electron/Tailwind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: npm i -g pnpm@9

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm -r lint

      - name: Unit Tests
        run: pnpm -r test -- --ci --reporter=default

      - name: Build Renderer
        run: pnpm -C apps/renderer build

      - name: Build Main
        run: pnpm -C apps/main build
